# src/main/resources/application-docker.properties

# DOCKER ORTAM AYARLARI
spring.config.import=
spring.cloud.vault.enabled=false
spring.cloud.vault.fail-fast=false
spring.cloud.vault.kv.enabled=false

spring.datasource.url=${USER_DOCKER_DB_URL:jdbc:postgresql://postgres-db:5432/users}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:user-service}
spring.flyway.table=user_flyway_history
