# src/main/resources/application-local.properties

# YEREL ORTAM AYARLARI
spring.datasource.url=jdbc:postgresql://localhost:5432/users
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.flyway.table=user_flyway_history
spring.config.import=
spring.cloud.vault.enabled=false
spring.cloud.vault.fail-fast=false
spring.cloud.vault.kv.enabled=false

spring.datasource.url=${USER_LOCAL_DB_URL:jdbc:postgresql://localhost:5432/users}
spring.datasource.username=${POSTGRES_USER:dev_user}
spring.datasource.password=${POSTGRES_PASSWORD:dev_password}
spring.jpa.hibernate.ddl-auto=update

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}:${server.port}
spring.security.oauth2.resourceserver.jwt.enabled=true
