spring.config.import=
spring.cloud.vault.enabled=false
spring.cloud.vault.fail-fast=false
spring.cloud.vault.kv.enabled=false

spring.datasource.url=${PERMISSION_LOCAL_DB_URL:jdbc:postgresql://localhost:5432/users}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
permission.bootstrap.default-admin-assignments.enabled=true
security.jwt.secondary-user-jwk-set-uri=${SECURITY_JWT_SECONDARY_USER_JWK_SET_URI:http://localhost:8088/oauth2/jwks}
security.jwt.secondary-issuer=${SECURITY_JWT_SECONDARY_ISSUER:auth-service}
security.jwt.secondary-audience=${SECURITY_JWT_SECONDARY_AUDIENCE:}
security.jwt.secondary-allowed-client-ids=${SECURITY_JWT_SECONDARY_ALLOWED_CLIENT_IDS:}
security.internal-api-key.value=${PERMISSION_SERVICE_INTERNAL_API_KEY:dev-local-audit-mirror-key}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}:${server.port}
