spring.config.import=
spring.cloud.vault.enabled=false
spring.cloud.vault.fail-fast=false
spring.cloud.vault.kv.enabled=false

spring.datasource.url=${PERMISSION_LOCAL_DB_URL:jdbc:postgresql://localhost:5432/users}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
permission.bootstrap.default-admin-assignments.enabled=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}:${server.port}
