spring:
  config:
    import:
      - vault://secret/${VAULT_SECRET_PREFIX:stage}/db/auth-service
      - vault://secret/${VAULT_SECRET_PREFIX:stage}/jwt/auth-service
  cloud:
    vault:
      enabled: true
      authentication: ${VAULT_AUTH_METHOD:TOKEN}
      token: ${VAULT_TOKEN:}
      app-role:
        role-id: ${VAULT_ROLE_ID:}
        secret-id: ${VAULT_SECRET_ID:}
        app-role-path: approle
      kv:
        enabled: true
        backend: secret
      uri: ${VAULT_URI:https://vault:8200}
      scheme: ${VAULT_SCHEME:https}
      fail-fast: ${VAULT_FAIL_FAST:true}
      ssl:
        trust-store: ${VAULT_TRUSTSTORE:}
        trust-store-type: PEM
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/realms/serban}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8081/realms/serban/protocol/openid-connect/certs}
