# src/main/resources/application-local.properties

# YEREL ORTAM AYARLARI
spring.config.import=
spring.cloud.vault.enabled=false
spring.cloud.vault.fail-fast=false
spring.cloud.vault.kv.enabled=false

spring.datasource.url=${AUTH_LOCAL_DB_URL:jdbc:postgresql://localhost:5432/users}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update

security.service-jwt.private-key=
security.service-jwt.public-key=

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.security.oauth2.resourceserver.jwt.enabled=false
