# src/main/resources/application-docker.properties

# DOCKER ORTAM AYARLARI
spring.config.import=
spring.cloud.vault.enabled=false
spring.cloud.vault.fail-fast=false
spring.cloud.vault.kv.enabled=false

spring.datasource.url=${AUTH_DOCKER_DB_URL:jdbc:postgresql://postgres-db:5432/${AUTH_DB_NAME:users}}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update

security.service-jwt.private-key=
security.service-jwt.public-key=

eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka

auth.tokens.verification-base-url=${AUTH_VERIFICATION_BASE_URL:http://host.docker.internal:3000/verify-email}
auth.tokens.reset-base-url=${AUTH_RESET_BASE_URL:http://host.docker.internal:3000/reset-password}
