# src/main/resources/application-docker.properties

# DOCKER ORTAM AYARLARI
spring.config.import=
spring.cloud.vault.enabled=false
spring.cloud.vault.fail-fast=false
spring.cloud.vault.kv.enabled=false

spring.datasource.url=${VARIANT_DB_URL:jdbc:postgresql://postgres-db:5432/users}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://discovery-server:8761/eureka}
spring.flyway.table=variant_flyway_history
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:variant-service}

# OpenFGA
erp.openfga.enabled=${ERP_OPENFGA_ENABLED:true}
erp.openfga.api-url=${ERP_OPENFGA_API_URL:http://openfga:8080}
erp.openfga.store-id=${ERP_OPENFGA_STORE_ID:}
erp.openfga.model-id=${ERP_OPENFGA_MODEL_ID:}
erp.openfga.dev-scope.super-admin=false
