# Varsayılan olarak 'local' profilini aktif et.
spring.profiles.active=local

# --- ORTAK AYARLAR ---
# Servisin adını ve çalışacağı portu belirtiyoruz
spring.application.name=discovery-server
server.port=8761

# Eureka bir sunucu olduğu için, kendisini başka bir sunucuya kaydetmeye çalışmamalıdır.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Sunucu Ayarları
eureka.server.wait-time-in-ms-when-sync-empty=0

# Actuator Ayarları
management.endpoints.web.exposure.include=health,info