spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/serban
          jwk-set-uri: http://keycloak:8080/realms/serban/protocol/openid-connect/certs
