# src/main/resources/application-local.properties

# YEREL ORTAM AYARLARI
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.registry-fetch-interval-seconds=5
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}:${server.port}
spring.security.oauth2.resourceserver.jwt.enabled=false
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins[0]=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins[1]=http://127.0.0.1:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins[2]=http://localhost:8082
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins[3]=http://127.0.0.1:8082
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers[0]=Authorization
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers[1]=Content-Type
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers[2]=X-Trace-Id
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers[3]=X-Correlation-Id
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods[0]=GET
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods[1]=POST
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods[2]=PUT
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods[3]=DELETE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods[4]=PATCH
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods[5]=OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true
