# src/main/resources/application-local.properties

# YEREL ORTAM AYARLARI
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}:${server.port}
spring.security.oauth2.resourceserver.jwt.enabled=false
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[0]=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[1]=http://127.0.0.1:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
